services:
  express-typescript-docker:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: BackendDev.Dockerfile
    volumes:
      - ./:/app
    container_name: ecommerce-api
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev

  nginx:
    build:
      context: .
      dockerfile: Nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - express-typescript-docker