services:
  express-typescript-docker:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: BackendDev.Dockerfile
    volumes:
        - ./backend:/usr/app
        - /usr/app/node_modules
    container_name: ecommerce-api
    expose:
      - '3000'
    command: yarn dev

  react-frontend-docker:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: FrontendDev.Dockerfile
    volumes:
      - ./frontend/e-commerce:/usr/app
      - /usr/app/node_modules
    container_name: ecommerce-frontend
    expose:
      - '3001:3001'
    command: yarn dev

  # cypress:
  #   build:
  #     context: .
  #     dockerfile: Cypress.Dockerfile
  #   depends_on:
  #     - react-frontend-docker
  #   environment:
  #     - CYPRESS_BASE_URL=http://ecommerce-frontend:3001
  #   # entrypoint: "/bin/sh -c 'yarn start-server-and-test dev http://react-frontend-docker:3001 cypress:run'"

  nginx:
    build:
      context: .
      dockerfile: Nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - express-typescript-docker
      - react-frontend-docker
    
  redis:
    image: redis:7.4-alpine
    expose:
      - "6379:6379"